services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - '80:80'
    depends_on:
      - static
  static:
    image: trojaner/trojaner-page
    build:
      context: .
      dockerfile: Dockerfile.static