FROM node:lts-alpine

# create and set workdir
WORKDIR /usr/src/trojaner-web

# install dependencies 
COPY package.json ./
COPY yarn.lock ./
RUN yarn install --frozen-lockfile
RUN yarn global add typescript

# copy pages to work dir
COPY ./static ./

RUN tsc