# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and compile it to typescript
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: TypeScript compilation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Typescript compiler
        uses: iCrawl/action-tsc@v1
